#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : clamav
Version  : 0.100.0
Release  : 3
URL      : https://www.clamav.net/downloads/production/clamav-0.100.0.tar.gz
Source0  : https://www.clamav.net/downloads/production/clamav-0.100.0.tar.gz
Summary  : A GPL virus scanner
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause BSL-1.0 GPL-2.0 LGPL-2.1 MIT NCSA NTP Zlib bzip2-1.0.6
Requires: clamav-bin
Requires: clamav-lib
Requires: clamav-doc
Requires: clamav-config
BuildRequires : bison
BuildRequires : bzip2-dev
BuildRequires : check
BuildRequires : cmake
BuildRequires : flex
BuildRequires : libxml2-dev
BuildRequires : llvm-dev
BuildRequires : openssl-dev
BuildRequires : pbr
BuildRequires : pcre-dev
BuildRequires : pip
BuildRequires : pkgconfig(ncurses)
BuildRequires : pkgconfig(ncursesw)
BuildRequires : pkgconfig(systemd)
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : systemd-dev
BuildRequires : xz-dev
BuildRequires : zlib-dev

%description
clam.exe is an extremely small (544 bytes!) MZ+PE executable that prints
a nice message :-) You can use it to test attachment scanning in your ClamAV
based mail scanner.

%package bin
Summary: bin components for the clamav package.
Group: Binaries
Requires: clamav-config

%description bin
bin components for the clamav package.


%package config
Summary: config components for the clamav package.
Group: Default

%description config
config components for the clamav package.


%package dev
Summary: dev components for the clamav package.
Group: Development
Requires: clamav-lib
Requires: clamav-bin
Provides: clamav-devel

%description dev
dev components for the clamav package.


%package doc
Summary: doc components for the clamav package.
Group: Documentation

%description doc
doc components for the clamav package.


%package lib
Summary: lib components for the clamav package.
Group: Libraries

%description lib
lib components for the clamav package.


%prep
%setup -q -n clamav-0.100.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1524311184
export CC=clang
export CXX=clang++
export LD=ld.gold
unset LDFLAGS
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1524311184
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/clamav-config
/usr/bin/clambc
/usr/bin/clamconf
/usr/bin/clamd
/usr/bin/clamdscan
/usr/bin/clamdtop
/usr/bin/clamscan
/usr/bin/freshclam
/usr/bin/sigtool

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/clamav-daemon.service
/usr/lib/systemd/system/clamav-daemon.socket
/usr/lib/systemd/system/clamav-freshclam.service

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libclamav.so
/usr/lib64/libclammspack.so
/usr/lib64/libclamunrar.so
/usr/lib64/libclamunrar_iface.so
/usr/lib64/pkgconfig/libclamav.pc
/usr/lib64/pkgconfig/libclammspack.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man5/*
%doc /usr/share/man/man8/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libclamav.so.7
/usr/lib64/libclamav.so.7.1.1
/usr/lib64/libclammspack.so.0
/usr/lib64/libclammspack.so.0.1.0
/usr/lib64/libclamunrar.so.7
/usr/lib64/libclamunrar.so.7.1.1
/usr/lib64/libclamunrar_iface.so.7
/usr/lib64/libclamunrar_iface.so.7.1.1
